### PR TITLE
updated submodule

### PR DESCRIPTION
**Pull request by floAr**

### CODE REVIEW

**Comment by pRizz** [comment]
Thanks for the PR. I am going to have to wait before merging this in though.

**Comment by pRizz** [comment]
I made a mistake in merging this. Your commit hash is not present in my submodule since I did a squash merge in the submodule. Therefore, I have to manually merge in the good submodule commit id.

**Comment by pRizz** [comment]
@floAr I updated the spammer on my website, just an fyi:
http://prizziota.com/iota-transaction-spammer-webapp/index.html
and
https://prizziota.com/iota-transaction-spammer-webapp/index.html

**Comment by wonkytonky** [comment]
2017-11-01T04:13:28.233Z: Error occurred while checking if node is synced

**Comment by pRizz** [comment]
It might take some time for AWS to propagate the update all over the world :)

**Comment by pRizz** [comment]
Give it a day

**Comment by wonkytonky** [comment]
hi, it works now.  thanks!  just saw some spamming work   .. good job guys..  realy appreciate this spammer tool

**Pull request merged**
